version: "3.9"
   
services:
  client:
    image: camsenec/protocol_testbed_packet:${TAG}
    stdin_open: true 
    tty: true
    volumes:
      - ./out:/app/out
    environment:
      - PROTOCOL_TESTBED_ADDRESS=16.170.140.181
      - PROTOCOL_TESTBED_PORT=8100
      - PROTOCOL_TESTBED_STPORT=8101
      - PROTOCOL_TESTBED_BUFSIZE=10000
      - PROTOCOL_TESTBED_UDP_TARGET=40
      - PROTOCOL_TESTBED_STPORTBW=40M
      #- PROTOCOL_TESTBED_FILE=somefile
    
  server:
    image: camsenec/protocol_testbed_packet:${TAG}
    stdin_open: true
    tty: true
    volumes:
      - ./out:/app/out
    ports:
      - "8100:8100"
      - "8101:8101"
      - "8100:8100/udp"
      - "8101:8101/udp"
    environment:
      - PROTOCOL_TESTBED_PORT=8100
      - PROTOCOL_TESTBED_STPORT=8101
      #- PROTOCOL_TESTBED_FILE=somefile



